# Generated by Django 3.0.5 on 2020-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc',
            name='bno',
            field=models.IntegerField(),
        ),
    ]
